services:
  - type: web
    name: chemical-equipment-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11
